### ISSUE TITLE
ROOT docker group ID

### ISSUE THREAD

**Issue by henryiii** [root-project/rootspi#25] opened 2017-08-18 14:49 UTC
When using the ROOT docker container, I get
```
$ docker run -it rootproject/root-ubuntu16 bash
groups: cannot find name for group ID 2735
sftnight@99a7747425dd:/$
```

The output of `id`:
```
uid=14806(sftnight) gid=2735 groups=2735
```

And that group is not listed in `/etc/group`.

Besides the warning, it might be causing some issues when I'm making a new Dockerfile using this as the base image and then using CMake (it can't make some files inside the build directory).

**Comment by henryiii** [comment] 2017-08-18 14:57
The warning goes away if
```
USER sftnight
```

Is replaced by

```
USER sftnight:sftnight
```

Though my CMake errors are still showing up.

**Comment by martinmine** [comment] 2017-08-18 15:12
Hi @henryiii, thanks for your report :) This was fixed earlier today in commit f74b12db949758bde9766a2edea78859abe4c20b and has therefore not yet reached the nightly build for the :latest tag yet. I've triggered a new build of this that will arrive shortly on the :latest tag. You can however use the :snapshot tag and you will not see this. I will close this issue and your PR once the container is out and I see this resolved.

**Comment by henryiii** [comment] 2017-08-18 15:26
I found the problem with the errors; when I run `WORKDIR /non/existent/dir`, it makes it, but with `root` permissions. `WORKDIR` is not in the list of commands that `USER` affects.

Thanks!

**Comment by martinmine** [comment] 2017-08-18 15:54
I see some workarounds for your issue. One way is to have `USER root` before `RUN` and use the root user. Another option would be to run `sudo chown` on the directory you specify in WORKDIR. 
I see this as a bit problematic as it leaves clutter in your Dockerfile related to dealing with permissions. OTOH, this is according to this https://github.com/moby/moby/issues/1295#issuecomment-269058662 comment expected behavior when setting a USER. The reason we wanted to ship containers with a user is to avoid running ROOT as super user by default and simplify some permission handling in our building infra. I'm going to close this for now, but if you have any advice on how to deal with this in a cleaner or better way, please let me know! :) 
And have a nice weekend!

**Closed by martinmine** 2017-08-18 15:54 UTC

**Comment by henryiii** [comment] 2017-08-18 16:14
Thanks! I'm going with explicitly making the directory first with `RUN mkdir`, since that at least is prettier than `chown`, and skips an explicit mention of the user. So the final Dockerfile is:

```
FROM rootproject/root-ubuntu16:latest
LABEL maintainer Henry Schreiner <henry.schreiner@uc.edu>

# Updated 2017-8-18
WORKDIR ${HOME}
RUN git clone --branch=stable --recursive https://github.com/GooFit/GooFit.git

RUN mkdir ${HOME}/GooFit/build
WORKDIR ${HOME}/GooFit/build
RUN cmake .. -DGOOFIT_DEVICE=OMP && \
    make -j$(nproc)

CMD ["bash"]
```

Have a nice weekend too! Cheers.
